### ISSUE TITLE
无法自动添加mod

### ISSUE THREAD

**Issue by Syuvii** [miracleEverywhere/dst-management-platform-api#7]
该系统启动后，能够成功启动游戏，但我配置的modoverrides.lua文件不生效，并且我在Steam/steamapps/common文件夹下没有看见Don't Starve Together Dedicated Server

**Comment by miracleEverywhere** [comment]
mod文件会自动下载至dst/mods和dst/ugc_mods这两个目录，目前自动下载mod官方有bug，在dmp的帮助页面可以进行一键修复，存档导入功能有无法自动下载mod的bug，将在下个版本修复
